#!/usr/bin/env python3
"""Embed a verified package identity; public qualification must precede release."""
import argparse
import hashlib
import json
from pathlib import Path
import pack


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--package', required=True)
    args = parser.parse_args()
    root = Path(args.package)
    data = (root/'manifest.json').read_bytes()
    digest = hashlib.sha256(data).hexdigest()
    receipt = json.loads((root/'build-receipt.json').read_text())
    assert digest == (root/'manifest.sha256').read_text().strip() == receipt['manifestSHA256']
    assert receipt['allOriginalHashesVerified'] and receipt['roundtripVerified'] and receipt['completeCoverage']
    assert json.loads(data)['files'] == pack.pins()
    assert data.endswith(b'\n') and b'"""#' not in data
    text = '// Generated by Tools/slotpack/embed.py. Do not hand-edit.\n'
    text += 'extension PinnedTransport {\n'
    text += f'    static let manifestSHA256 = "{digest}"\n'
    text += '    static let manifestJSON = #"""\n' + data.decode().removesuffix('\n')
    text += '\n"""# + "\\n"\n}\n'
    (pack.ROOT/'Sources/Slotstream/PinnedTransportManifest.swift').write_text(text)
    print(digest)


if __name__ == '__main__': main()
