#!/bin/bash
# Build llms-full.txt: every user-facing doc in one file, for agents that want
# a single fetch (llms.txt is the index). --check fails when the committed
# file is stale, so the static gates catch a doc edit without a regenerate.
set -euo pipefail
cd "$(dirname "$0")/.."

SOURCES=(README.md docs/CLI.md docs/API.md docs/TROUBLESHOOTING.md docs/HARDWARE.md CHANGELOG.md)

render() {
  echo "# slotstream: full documentation"
  echo
  echo "Generated by Tools/llms_full.sh from ${SOURCES[*]}. Edit those, then rerun it."
  echo "Relative links below point at the same sections, which are all in this file."
  for f in "${SOURCES[@]}"; do
    echo
    echo
    echo "<!-- ===== $f ===== -->"
    echo
    cat "$f"
  done
}

if [ "${1:-}" = "--check" ]; then
  if ! diff -q <(render) llms-full.txt >/dev/null 2>&1; then
    echo "llms-full.txt is stale: run Tools/llms_full.sh and commit the result" >&2
    exit 1
  fi
  echo "llms-full.txt is current"
else
  render > llms-full.txt
  echo "wrote llms-full.txt ($(wc -l < llms-full.txt | tr -d ' ') lines)"
fi
