#!/usr/bin/env python3
"""Regenerate MEASUREMENTS.md and PLAN.md from the brain's records.

The records under db/records/measurements, db/records/design, and
db/records/plan are the authority; each one is a section (`doc` names the
document, `level` the heading depth, `order` the position). This script
concatenates them into the two documents readers open. `--check` exits 1
when a committed document differs from what its records generate, which is
the CI gate against editing the generated file instead of the record.

Standard library only, and it parses frontmatter itself, so a contributor
without dbmd can still regenerate the documents.

Sections are rendered with exactly one blank line between them, so a record
body's trailing whitespace never matters. That normalization is the one
difference from the documents as they were lifted on 2026-09-02: one heading
in MEASUREMENTS.md had no blank line before it and now has one.
"""
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
STORE = os.path.join(ROOT, 'db')
DOCS = {
    'measurements': {
        'file': 'MEASUREMENTS.md',
        'folders': ['records/measurements'],
    },
    'plan': {
        'file': 'PLAN.md',
        'folders': ['records/design', 'records/plan'],
    },
}


def banner(doc):
    folders = ', '.join('db/' + f + '/' for f in DOCS[doc]['folders'])
    return ('<!-- Generated by Tools/projections.py from ' + folders +
            ' Edit the records, then run the script; this file is a projection. -->\n\n')


def unquote(value):
    value = value.strip()
    if len(value) >= 2 and value[0] == "'" and value[-1] == "'":
        return value[1:-1].replace("''", "'")
    if len(value) >= 2 and value[0] == '"' and value[-1] == '"':
        out, i, inner = [], 0, value[1:-1]
        while i < len(inner):
            c = inner[i]
            if c == '\\' and i + 1 < len(inner):
                nxt = inner[i + 1]
                if nxt == 'n':
                    out.append('\n')
                elif nxt == 't':
                    out.append('\t')
                elif nxt == 'u' and i + 5 < len(inner):
                    out.append(chr(int(inner[i + 2:i + 6], 16)))
                    i += 4
                else:
                    out.append(nxt)
                i += 2
                continue
            out.append(c)
            i += 1
        return ''.join(out)
    return value


def read_record(path):
    """Return (frontmatter scalars, verbatim body). Lists are skipped."""
    with open(path, encoding='utf-8') as fh:
        text = fh.read()
    if not text.startswith('---\n'):
        raise SystemExit('%s: no frontmatter' % path)
    end = text.find('\n---\n', 4)
    if end < 0:
        raise SystemExit('%s: unterminated frontmatter' % path)
    fm = {}
    for line in text[4:end].split('\n'):
        m = re.match(r'^([A-Za-z0-9_-]+):(.*)$', line)
        if not m:
            continue
        key, raw = m.group(1), m.group(2)
        if raw.strip() == '':
            continue
        fm[key] = unquote(raw)
    body = text[end + len('\n---\n'):]
    return fm, body


def sections(doc):
    out = []
    for folder in DOCS[doc]['folders']:
        full = os.path.join(STORE, folder)
        if not os.path.isdir(full):
            raise SystemExit('missing folder %s' % full)
        for name in sorted(os.listdir(full)):
            if not name.endswith('.md') or name == 'index.md':
                continue
            fm, body = read_record(os.path.join(full, name))
            if fm.get('doc') != doc:
                raise SystemExit('%s/%s: doc is %r, expected %r' % (folder, name, fm.get('doc'), doc))
            for key in ('order', 'level', 'title'):
                if key not in fm:
                    raise SystemExit('%s/%s: missing %s' % (folder, name, key))
            out.append((int(fm['order']), folder + '/' + name, int(fm['level']), fm['title'], body))
    out.sort()
    orders = [o for o, _, _, _, _ in out]
    dupes = sorted({o for o in orders if orders.count(o) > 1})
    if dupes:
        raise SystemExit('%s: duplicate order values %s' % (doc, dupes))
    return out


def render(doc):
    """Heading, body, one blank line, next heading; a single newline at the end.

    Bodies are normalized at the end (trailing newlines stripped, then exactly
    one blank line before the next section), so a record survives whitespace
    formatting and a section is separated from the next the way both documents
    always were.
    """
    parts = [banner(doc)]
    secs = sections(doc)
    for i, (_, _, level, title, body) in enumerate(secs):
        parts.append('#' * level + ' ' + title + '\n')
        parts.append(body.rstrip('\n'))
        parts.append('\n' if i == len(secs) - 1 else '\n\n')
    return ''.join(parts)


def main(argv):
    check = '--check' in argv
    only = [a for a in argv if not a.startswith('--')]
    status = 0
    for doc, spec in DOCS.items():
        if only and doc not in only and spec['file'] not in only:
            continue
        target = os.path.join(ROOT, spec['file'])
        generated = render(doc)
        current = open(target, encoding='utf-8').read() if os.path.exists(target) else None
        if generated == current:
            print('%s is current' % spec['file'])
            continue
        if check:
            print('%s differs from its records: run Tools/projections.py' % spec['file'], file=sys.stderr)
            status = 1
            continue
        with open(target, 'w', encoding='utf-8') as fh:
            fh.write(generated)
        print('wrote %s (%d lines)' % (spec['file'], generated.count('\n')))
    return status


if __name__ == '__main__':
    sys.exit(main(sys.argv[1:]))
